### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by sashton** [cldwalker/smart-ignore#3]
Hey @cldwalker, I have a question, not really an issue. How do you build smart-ignore? There isn't mention of cljsbuild in project.clj.  What build command are you using?

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 4 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/smart-ignore#3). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by sashton** [comment]
I figured it out. At https://github.com/priyatam/lighttable-plugin-guide it mentions the built-in LT command: 'build file or project'. That seemed to work, so I assume that's what you did. Do you know if that's the preferred way to build a plugin, rather than with Leiningen?
